// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20250530220440_AddFilesTable")]
    partial class AddFilesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Peaks.Peak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Peaks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 1603,
                            Name = "Śnieżka",
                            RegionID = 22
                        },
                        new
                        {
                            Id = 2,
                            Height = 1346,
                            Name = "Rysy",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 3,
                            Height = 2050,
                            Name = "Giewont",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 4,
                            Height = 1367,
                            Name = "Czupel",
                            RegionID = 3
                        });
                });

            modelBuilder.Entity("Domain.Regions.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tatry"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pieniny"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beskid Śląski"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beskid Żywiecki"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beskid Mały"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beskid Makowski"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beskid Wyspowy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gorce"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Beskid Sądecki"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Beskid Niski"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bieszczady"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Góry Świętokrzyskie"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Góry Sowie"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Góry Stołowe"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Góry Bystrzyckie"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Góry Orlickie"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Góry Bialskie"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Góry Złote"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Góry Opawskie"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Góry Bardzkie"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Masyw Śnieżnika"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Karkonosze"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Góry Izerskie"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Rudawy Janowickie"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Sudety Wałbrzyskie"
                        });
                });

            modelBuilder.Entity("Domain.Trips.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TripDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 23.7f,
                            Duration = 8f,
                            Height = 1000f,
                            RegionID = 1,
                            TripDay = new DateOnly(2020, 12, 1)
                        },
                        new
                        {
                            Id = 2,
                            Distance = 14.2f,
                            Duration = 4f,
                            Height = 620f,
                            RegionID = 22,
                            TripDay = new DateOnly(2023, 4, 7)
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateOnly(2002, 4, 15),
                            Email = "mistrzbiznesu@wp.pl",
                            Name = "Janusz"
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateOnly(1995, 8, 20),
                            Email = "kasia.wandziak@wp.pl",
                            Name = "Kasia"
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateOnly(1988, 3, 2),
                            Email = "marek.kowalski@gmail.com",
                            Name = "Marek"
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateOnly(1990, 12, 11),
                            Email = "ewa.nowak@outlook.com",
                            Name = "Ewa"
                        });
                });

            modelBuilder.Entity("Domain.Peaks.Peak", b =>
                {
                    b.HasOne("Domain.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Trips.Trip", b =>
                {
                    b.HasOne("Domain.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
