name: Deploy Frontend to Pages

on:
  push:
    branches: ["master"]
    paths: ["Frontend/**"] # Only run when client code changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.20.0'
          cache: 'pnpm'
          cache-dependency-path: ./Frontend/pnpm-lock.yaml

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install and Build
        working-directory: Frontend
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend/dist